### ISSUE TITLE
[Bug]: "EditRegistry" with "5" argument(s): "Invalid registry value type"

### ISSUE THREAD

**Issue by zoltrons** [HotCakeX/Harden-Windows-Security#313]
### Tools category

Harden Windows Security Module

### Does Your System Meet The Requirements?

- [X] Yes, I acknowledge that I've read the requirements and my system meets them. 👍

### Is your Windows Installation Genuine?

- [X] Yes, I acknowledge that the installation media of the Windows OS I used the tool on was downloaded from the official Microsoft website and I didn't tamper or modify it. 💯

### Did You Read The Frequently Asked Questions?

- [X] Yes, I've referred to the [FAQs](https://github.com/HotCakeX/Harden-Windows-Security/wiki/Answers-to-the-Basic-Frequently-Asked-Questions) and my issue is not covered/explained in there.

### Please Explain The Bug

When I tried to apply Miscellaneous Configurations, Edge Browser configurations and Non-Admin Commands, I got this error "Exception calling "EditRegistry" with "5" argument(s): "Invalid registry value type"".

### Error Details

```console
Exception: C:\Users\user\OneDrive\Belgeler\PowerShell\Modules\Harden-Windows-Security-Module\0.5.2\Shared\HardeningFunctions.ps1:1611
Line |
1611 |  …             [HardeningModule.RegistryEditor]::EditRegistry($Item.Path …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception calling "EditRegistry" with "5" argument(s): "Invalid registry value type"
PS C:\Users\user> Get-Error

Exception             :
    Type                        : System.Management.Automation.MethodInvocationException
    ErrorRecord                 :
        Exception             :
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : Exception calling "EditRegistry" with "5" argument(s): "Invalid registry value type"
            HResult : -2146233087
        CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
        FullyQualifiedErrorId : ArgumentException
        InvocationInfo        :
            ScriptLineNumber : 1611
            OffsetInLine     : 21
            HistoryId        : 3
            ScriptName       : C:\Users\user\OneDrive\Belgeler\PowerShell\Modules\Harden-Windows-Security-Module\0.5.2
\Shared\HardeningFunctions.ps1
            Line             : [HardeningModule.RegistryEditor]::EditRegistry($Item.Path, $Item.Key, $Item.Value, $Item
.Type, $Item.Action)

            Statement        : [HardeningModule.RegistryEditor]::EditRegistry($Item.Path, $Item.Key, $Item.Value, $Item
.Type, $Item.Action)
            PositionMessage  : At C:\Users\user\OneDrive\Belgeler\PowerShell\Modules\Harden-Windows-Security-Module\0.
5.2\Shared\HardeningFunctions.ps1:1611 char:21
                               + …             [HardeningModule.RegistryEditor]::EditRegistry($Item.Path …
                               +               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            PSScriptRoot     : C:\Users\user\OneDrive\Belgeler\PowerShell\Modules\Harden-Windows-Security-Module\0.5.2
\Shared
            PSCommandPath    : C:\Users\user\OneDrive\Belgeler\PowerShell\Modules\Harden-Windows-Security-Module\0.5.2
\Shared\HardeningFunctions.ps1
            CommandOrigin    : Internal
        ScriptStackTrace      : at Invoke-MiscellaneousConfigurations, C:\Users\user\OneDrive\Belgeler\PowerShell\Modu
les\Harden-Windows-Security-Module\0.5.2\Shared\HardeningFunctions.ps1: line 1611
                                at Protect-WindowsSecurity<Process>, C:\Users\user\OneDrive\Belgeler\PowerShell\Module
s\Harden-Windows-Security-Module\0.5.2\Core\Protect-WindowsSecurity.psm1: line 1155
                                at <ScriptBlock>, <No file>: line 1
    WasThrownFromThrowStatement : True
    TargetSite                  :
        Name          : CheckActionPreference
        DeclaringType : [System.Management.Automation.ExceptionHandlingOps]
        MemberType    : Method
        Module        : System.Management.Automation.dll
    Message                     : Exception calling "EditRegistry" with "5" argument(s): "Invalid registry value type"
    Data                        : System.Collections.ListDictionaryInternal
    InnerException              :
        Type       : System.ArgumentException
        Message    : Invalid registry value type
        TargetSite :
            Name          : EditRegistry
            DeclaringType : [HardeningModule.RegistryEditor]
            MemberType    : Method
            Module        : xixwqx3p.rmb.dll
        Source     : xixwqx3p.rmb
        HResult    : -2147024809
        StackTrace :
   at HardeningModule.RegistryEditor.EditRegistry(String path, String key, String value, String type, String action)
   at CallSite.Target(Closure, CallSite, Type, Object, Object, Object, Object, Object)
    Source                      : System.Management.Automation
    HResult                     : -2146233087
    StackTrace                  :
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception ex
ception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
FullyQualifiedErrorId : ArgumentException
InvocationInfo        :
    ScriptLineNumber : 1611
    OffsetInLine     : 21
    HistoryId        : 3
    ScriptName       : C:\Users\user\OneDrive\Belgeler\PowerShell\Modules\Harden-Windows-Security-Module\0.5.2\Shared\
HardeningFunctions.ps1
    Line             : [HardeningModule.RegistryEditor]::EditRegistry($Item.Path, $Item.Key, $Item.Value, $Item.Type, $
Item.Action)

    Statement        : [HardeningModule.RegistryEditor]::EditRegistry($Item.Path, $Item.Key, $Item.Value, $Item.Type, $
Item.Action)
    PositionMessage  : At C:\Users\user\OneDrive\Belgeler\PowerShell\Modules\Harden-Windows-Security-Module\0.5.2\Shar
ed\HardeningFunctions.ps1:1611 char:21
                       + …             [HardeningModule.RegistryEditor]::EditRegistry($Item.Path …
                       +               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    PSScriptRoot     : C:\Users\user\OneDrive\Belgeler\PowerShell\Modules\Harden-Windows-Security-Module\0.5.2\Shared
    PSCommandPath    : C:\Users\user\OneDrive\Belgeler\PowerShell\Modules\Harden-Windows-Security-Module\0.5.2\Shared\
HardeningFunctions.ps1
    CommandOrigin    : Internal
ScriptStackTrace      : at Invoke-MiscellaneousConfigurations, C:\Users\user\OneDrive\Belgeler\PowerShell\Modules\Hard
en-Windows-Security-Module\0.5.2\Shared\HardeningFunctions.ps1: line 1611
                        at Protect-WindowsSecurity<Process>, C:\Users\user\OneDrive\Belgeler\PowerShell\Modules\Harden
-Windows-Security-Module\0.5.2\Core\Protect-WindowsSecurity.psm1: line 1155
                        at <ScriptBlock>, <No file>: line 1
```

**Comment by HotCakeX** [comment]
I couldn't reproduce it so far, i need more info. What do you see when you run this command?

```powershell
Get-Culture
```

**Comment by HotCakeX** [comment]
Have you modified the module files? E.g, opened the CSV files in VS code, format them, align them etc.?

The error message is clear but it shouldn't be thrown unless the module files are modified.

Try closing PowerShell, go to `C:\Users\user\OneDrive\Belgeler\PowerShell\Modules` and delete the `Harden-Windows-Security-Module` folder, then reinstall it again using this command

```powershell
Install-Module -Name 'Harden-Windows-Security-Module' -Force
```

let me know how it goes

**Comment by zoltrons** [comment]
> Have you modified the module files? E.g, opened the CSV files in VS code, format them, align them etc.?
> 
> The error message is clear but it shouldn't be thrown unless the module files are modified.
> 
> Try closing PowerShell, go to `C:\Users\user\OneDrive\Belgeler\PowerShell\Modules` and delete the `Harden-Windows-Security-Module` folder, then reinstall it again using this command
> 
> ```powershell
> Install-Module -Name 'Harden-Windows-Security-Module' -Force
> ```
> 
> let me know how it goes

I didn't modify any of the file. I tried your suggestion, but I still got the same error.

Get-Culture output:

LCID             Name             DisplayName
----             ----             -----------
1055             tr-TR            Turkish (Turkey)

**Comment by HotCakeX** [comment]
@zoltrons Thank you, that was very helpful and I found the issue, will release a new update to fix it today!
