### ISSUE TITLE
[Bug]: Exception calling "Initialize" with "1" argument(s): "WMI query for 'MSFT_MpPreference' failed.

### ISSUE THREAD

**Issue by 0x11DFE** [HotCakeX/Harden-Windows-Security#352]
### Tools category

Harden Windows Security Module

### Does Your System Meet The Requirements?

- [X] Yes, I acknowledge that I've read the requirements and my system meets them. 👍

### Is your Windows Installation Genuine?

- [X] Yes, I acknowledge that the installation media of the Windows OS I used the tool on was downloaded from the official Microsoft website and I didn't tamper or modify it. 💯

### Did You Read The Frequently Asked Questions?

- [X] Yes, I've referred to the [FAQs](https://github.com/HotCakeX/Harden-Windows-Security/wiki/Answers-to-the-Basic-Frequently-Asked-Questions) and my issue is not covered/explained in there.

### Please Explain The Bug

Whenever I try to use the tool, it returns the error specified in this issue title.
I believe it is due to my system not having Defender installed, As I don't primarily rely on it.

### Error Details

```console
Exception             :
    Type           : System.Management.Automation.MethodInvocationException
    ErrorRecord    :
        Exception             :
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : Exception calling "Initialize" with "1" argument(s): "WMI query for 'MSFT_MpPreference' failed:
Provider load failure "
            HResult : -2146233087
        CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
        FullyQualifiedErrorId : PowerShellExecutionException
        InvocationInfo        :
            ScriptLineNumber : 47
            OffsetInLine     : 9
            HistoryId        : 6
            ScriptName       : C:\Users\Administrator\Documents\PowerShell\Modules\Harden-Windows-Security-Module\0.6.5
\Core\Confirm-SystemCompliance.psm1
            Line             : [HardenWindowsSecurity.Initializer]::Initialize($VerbosePreference)

            Statement        : [HardenWindowsSecurity.Initializer]::Initialize($VerbosePreference)
            PositionMessage  : At C:\Users\Administrator\Documents\PowerShell\Modules\Harden-Windows-Security-Module\0.
6.5\Core\Confirm-SystemCompliance.psm1:47 char:9
                               +         [HardenWindowsSecurity.Initializer]::Initialize($VerbosePrefe …
                               +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            PSScriptRoot     :
C:\Users\Administrator\Documents\PowerShell\Modules\Harden-Windows-Security-Module\0.6.5\Core
            PSCommandPath    : C:\Users\Administrator\Documents\PowerShell\Modules\Harden-Windows-Security-Module\0.6.5
\Core\Confirm-SystemCompliance.psm1
            CommandOrigin    : Internal
        ScriptStackTrace      : at Confirm-SystemCompliance<Begin>, C:\Users\Administrator\Documents\PowerShell\Modules
\Harden-Windows-Security-Module\0.6.5\Core\Confirm-SystemCompliance.psm1: line 47
                                at <ScriptBlock>, <No file>: line 1
    TargetSite     :
        Name          : CheckActionPreference
        DeclaringType : [System.Management.Automation.ExceptionHandlingOps]
        MemberType    : Method
        Module        : System.Management.Automation.dll
    Message        : Exception calling "Initialize" with "1" argument(s): "WMI query for 'MSFT_MpPreference' failed:
Provider load failure "
    Data           : System.Collections.ListDictionaryInternal
    InnerException :
        Type           : HardenWindowsSecurity.PowerShellExecutionException
        TargetSite     :
            Name          : GetMpPreference
            DeclaringType : [HardenWindowsSecurity.MpPreferenceHelper]
            MemberType    : Method
            Module        : nijeypag.zsg.dll
        Message        : WMI query for 'MSFT_MpPreference' failed: Provider load failure
        InnerException :
            Type             : System.Management.ManagementException
            ErrorInformation : System.Management.ManagementBaseObject
            ErrorCode        : ProviderLoadFailure
            TargetSite       :
                Name          : ThrowWithExtendedInfo
                DeclaringType : [System.Management.ManagementException]
                MemberType    : Method
                Module        : System.Management.dll
            Message          : Provider load failure
            Source           : System.Management
            HResult          : -2146233087
            StackTrace       :
   at System.Management.ManagementException.ThrowWithExtendedInfo(ManagementStatus errorCode)
   at System.Management.ManagementObjectCollection.ManagementObjectEnumerator.MoveNext()
   at System.Management.ManagementObjectCollection.get_Count()
   at HardenWindowsSecurity.MpPreferenceHelper.GetMpPreference()
        Source         : nijeypag.zsg
        HResult        : -2146233088
        StackTrace     :
   at HardenWindowsSecurity.MpPreferenceHelper.GetMpPreference()
   at HardenWindowsSecurity.Initializer.Initialize(String VerbosePreference, Boolean IsConfirmationDuringRunTime)
   at CallSite.Target(Closure, CallSite, Type, Object)
    Source         : System.Management.Automation
    HResult        : -2146233087
    StackTrace     :
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception
exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object
inputToProcess)
   at System.Management.Automation.Cmdlet.DoBeginProcessing()
   at System.Management.Automation.CommandProcessorBase.DoBegin()
CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
FullyQualifiedErrorId : PowerShellExecutionException
InvocationInfo        :
    ScriptLineNumber : 47
    OffsetInLine     : 9
    HistoryId        : 6
    ScriptName       : C:\Users\Administrator\Documents\PowerShell\Modules\Harden-Windows-Security-Module\0.6.5\Core\Co
nfirm-SystemCompliance.psm1
    Line             : [HardenWindowsSecurity.Initializer]::Initialize($VerbosePreference)

    Statement        : [HardenWindowsSecurity.Initializer]::Initialize($VerbosePreference)
    PositionMessage  : At C:\Users\Administrator\Documents\PowerShell\Modules\Harden-Windows-Security-Module\0.6.5\Core
\Confirm-SystemCompliance.psm1:47 char:9
                       +         [HardenWindowsSecurity.Initializer]::Initialize($VerbosePrefe …
                       +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    PSScriptRoot     : C:\Users\Administrator\Documents\PowerShell\Modules\Harden-Windows-Security-Module\0.6.5\Core
    PSCommandPath    : C:\Users\Administrator\Documents\PowerShell\Modules\Harden-Windows-Security-Module\0.6.5\Core\Co
nfirm-SystemCompliance.psm1
    CommandOrigin    : Internal
ScriptStackTrace      : at Confirm-SystemCompliance<Begin>, C:\Users\Administrator\Documents\PowerShell\Modules\Harden-
Windows-Security-Module\0.6.5\Core\Confirm-SystemCompliance.psm1: line 47
                        at <ScriptBlock>, <No file>: line 1
```

**Comment by HotCakeX** [comment]
Hi, that's right. Since you checked the boxes acknowledging the requirements and having read the related documents, you are aware of it. Closing the issue.

**Comment by 0x11DFE** [comment]
> Hi, that's right. Since you checked the boxes acknowledging the requirements and having read the related documents, you are aware of it. Closing the issue.

Yes, I am, therefore I cannot suggest anyone to daily drive defender.
Plus, I believe this project should solely be towards Defender, but it actually has many more features outside Defender.
