### ISSUE TITLE
[Bug]: Harden Windows Security Module stops working when confirm and verify

### ISSUE THREAD

**Issue by kiro5678** [HotCakeX/Harden-Windows-Security#368]
![Screenshot 2024-10-19 115025](https://github.com/user-attachments/assets/37bb5eb8-375a-400b-8300-173c228988db)
### Tools category

Harden Windows Security Module

### Does Your System Meet The Requirements?

- [X] Yes, I acknowledge that I've read the requirements and my system meets them. 👍

### Is your Windows Installation Genuine?

- [X] Yes, I acknowledge that the installation media of the Windows OS I used the tool on was downloaded from the official Microsoft website and I didn't tamper or modify it. 💯

### Did You Read The Frequently Asked Questions?

- [X] Yes, I've referred to the [FAQs](https://github.com/HotCakeX/Harden-Windows-Security/wiki/Answers-to-the-Basic-Frequently-Asked-Questions) and my issue is not covered/explained in there.

### Please Explain The Bug

When checking the security settings application, the program stops working after applying the recommended security settings (I did not activate BitLocker)

### Error Details

```console
PowerShell 7.4.5
PS C:\Windows\System32> Protect-WindowsSecurity -GUI
MethodInvocationException: Exception calling "Run" with "1" argument(s): "One or more errors occurred. (PowerShell script execution failed: Error:
Element not found.  Category: NotSpecified Target:  Script StackTrace:  Exception Type:
System.Management.Automation.RemoteException StackTrace: )"


ErrorRecord                 : Exception calling "Run" with "1" argument(s): "One or more errors occurred. (PowerShell
                              script execution failed: Error: Element not found.

                              Category: NotSpecified
                              Target:
                              Script StackTrace:
                              Exception Type: System.Management.Automation.RemoteException
                              StackTrace: )"
WasThrownFromThrowStatement : False
TargetSite                  : Void CheckActionPreference(System.Management.Automation.Language.FunctionContext,
                              System.Exception)
Message                     : Exception calling "Run" with "1" argument(s): "One or more errors occurred. (PowerShell
                              script execution failed: Error: Element not found.

                              Category: NotSpecified
                              Target:
                              Script StackTrace:
                              Exception Type: System.Management.Automation.RemoteException
                              StackTrace: )"
Data                        : {[System.Management.Automation.Interpreter.InterpretedFrameInfo,
                              System.Management.Automation.Interpreter.InterpretedFrameInfo[]]}
InnerException              : System.AggregateException: One or more errors occurred. (PowerShell script execution
                              failed: Error: Element not found.

                              Category: NotSpecified
                              Target:
                              Script StackTrace:
                              Exception Type: System.Management.Automation.RemoteException
                              StackTrace: )
                               ---> System.Management.Automation.CmdletInvocationException: PowerShell script
                              execution failed: Error: Element not found.

                              Category: NotSpecified
                              Target:
                              Script StackTrace:
                              Exception Type: System.Management.Automation.RemoteException
                              StackTrace:
                               ---> System.InvalidOperationException: PowerShell script execution failed: Error:
                              Element not found.

                              Category: NotSpecified
                              Target:
                              Script StackTrace:
                              Exception Type: System.Management.Automation.RemoteException
                              StackTrace:
                                 at
                              HardenWindowsSecurity.PowerShellExecutor.<>c__DisplayClass0_0.<ExecuteScript>b__3(Object
                              sender, DataAddedEventArgs args)
                                 at System.Management.Automation.PSDataCollection`1.RaiseEvents(Guid psInstanceId,
                              Int32 index)
                                 at System.Management.Automation.PSDataCollection`1.InternalAddRange(Guid
                              psInstanceId, ICollection collection)
                                 at System.Management.Automation.Internal.PSDataCollectionStream`1.Write(Object obj,
                              Boolean enumerateCollection)
                                 at System.Management.Automation.Internal.Pipe.AddToPipe(Object obj)
                                 at
                              System.Management.Automation.MshCommandRuntime._WriteErrorSkipAllowCheck(ErrorRecord
                              errorRecord, Nullable`1 actionPreference, Boolean isFromNativeStdError)
                                 at System.Management.Automation.MshCommandRuntime.DoWriteError(Object obj)
                                 at System.Management.Automation.MshCommandRuntime.WriteError(ErrorRecord errorRecord,
                              Boolean overrideInquire)
                                 at Microsoft.PowerShell.Commands.InvokeCommandCommand.WriteStreamObjectsFromCollection
                              (IEnumerable`1 results)
                                 at Microsoft.PowerShell.Commands.InvokeCommandCommand.WriteJobResults(Boolean
                              nonblocking)
                                 at Microsoft.PowerShell.Commands.InvokeCommandCommand.EndProcessing()
                                 at System.Management.Automation.CommandProcessorBase.Complete()
                                 --- End of inner exception stack trace ---
                                 at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
                                 at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace
                              rs, Boolean performSyncInvoke)
                                 at
                              System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace
                              rsToUse, Boolean isSync)
                                 at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataColl
                              ection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
                                 at
                              System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1
                              input, PSDataCollection`1 output, PSInvocationSettings settings)
                                 at System.Management.Automation.PowerShell.Invoke[T]()
                                 at HardenWindowsSecurity.PowerShellExecutor.ExecuteScript(String script, Boolean
                              returnOutput, Boolean NonTerminatingErrors)
                                 at HardenWindowsSecurity.WindowsFeatureChecker.GetCapabilityState(String
                              capabilityName)
                                 at HardenWindowsSecurity.WindowsFeatureChecker.CheckWindowsFeatures()
                                 at HardenWindowsSecurity.ConfirmSystemComplianceMethods.<>c.<VerifyOptionalWindowsFeat
                              ures>b__13_0()
                                 at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread
                              threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object
                              state)
                              --- End of stack trace from previous location ---
                                 at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread
                              threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object
                              state)
                                 at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread
                              threadPoolThread)
                              --- End of stack trace from previous location ---
                                 at HardenWindowsSecurity.ConfirmSystemComplianceMethods.RunComplianceMethodsInParallel
                              Async(String[] methodNames)
                                 --- End of inner exception stack trace ---
                                 at HardenWindowsSecurity.ConfirmSystemComplianceMethods.OrchestrateComplianceChecks(St
                              ring[] methodNames)
                                 at HardenWindowsSecurity.InvokeConfirmation.Invoke(String[] Categories)
                                 at HardenWindowsSecurity.GUIMain.NavigationVM.<>c__DisplayClass4_0.<Confirm>b__10()
                                 at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread
                              threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object
                              state)
                              --- End of stack trace from previous location ---
                                 at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread
                              threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object
                              state)
                                 at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread
                              threadPoolThread)
                              --- End of stack trace from previous location ---
                                 at HardenWindowsSecurity.GUIMain.NavigationVM.<>c__DisplayClass4_0.<<Confirm>b__7>d.Mo
                              veNext()
                              --- End of stack trace from previous location ---
                                 at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
                                 at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback,
                              Object args, Int32 numArgs)
                                 at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate
                              callback, Object args, Int32 numArgs, Delegate catchHandler)
                                 at System.Windows.Threading.DispatcherOperation.InvokeImpl()
                                 at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
                                 at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext,
                              ContextCallback callback, Object state)
                              --- End of stack trace from previous location ---
                                 at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext,
                              ContextCallback callback, Object state)
                                 at
                              MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext
                              executionContext, ContextCallback callback, Object state)
                                 at System.Windows.Threading.DispatcherOperation.Invoke()
                                 at System.Windows.Threading.Dispatcher.ProcessQueue()
                                 at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr
                              wParam, IntPtr lParam, Boolean& handled)
                                 at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam,
                              Boolean& handled)
                                 at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback,
                              Object args, Int32 numArgs)
                                 at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate
                              callback, Object args, Int32 numArgs, Delegate catchHandler)
                                 at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority,
                              TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
                                 at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam,
                              IntPtr lParam)
                                 at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
                                 at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
                                 at System.Windows.Application.RunDispatcher(Object ignore)
                                 at System.Windows.Application.RunInternal(Window window)
                                 at CallSite.Target(Closure, CallSite, Application, Window)
HelpLink                    :
Source                      : System.Management.Automation
HResult                     : -2146233087
StackTrace                  :    at
                              System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext
                              funcContext, Exception exception)
                                 at
                              System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame
                              frame)
                                 at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(Interp
                              retedFrame frame)
                                 at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(Interp
                              retedFrame frame)

MyCommand             :
BoundParameters       : {}
UnboundArguments      : {}
ScriptLineNumber      : 364
OffsetInLine          : 17
HistoryId             : 1
ScriptName            : C:\Program Files\WindowsPowerShell\Modules\Harden-Windows-Security-Module\0.6.7\Core\Protect-Wi
                        ndowsSecurity.psm1
Line                  :                 [System.Void]
                        [HardenWindowsSecurity.GUIMain]::app.Run([HardenWindowsSecurity.GUIMain]::mainGUIWindow)

Statement             : [System.Void]
                        [HardenWindowsSecurity.GUIMain]::app.Run([HardenWindowsSecurity.GUIMain]::mainGUIWindow)
PositionMessage       : At C:\Program Files\WindowsPowerShell\Modules\Harden-Windows-Security-Module\0.6.7\Core\Protect
                        -WindowsSecurity.psm1:364 char:17
                        + …             [System.Void] [HardenWindowsSecurity.GUIMain]::app.Run([H …
                        +               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PSScriptRoot          : C:\Program Files\WindowsPowerShell\Modules\Harden-Windows-Security-Module\0.6.7\Core
PSCommandPath         : C:\Program Files\WindowsPowerShell\Modules\Harden-Windows-Security-Module\0.6.7\Core\Protect-Wi
                        ndowsSecurity.psm1
InvocationName        :
PipelineLength        : 0
PipelinePosition      : 0
ExpectingInput        : False
CommandOrigin         : Internal
DisplayScriptPosition :
```

**Comment by HotCakeX** [comment]
Hi,
Thanks for reporting but that's unfortunately an issue in Windows 11 24H2 and it happens when the legacy Internet explorer mode for Edge is removed but the system is not restarted. To solve that, after IE mode is removed, you need to restart the system and then things will work normally.

I've reported it to [Windows Insider team on X](https://x.com/CyberCakeX/status/1842186859897590020) and also filed a feedback [on feedback hub](https://aka.ms/AAskjrv) so i did my part, just have to wait and see when it will be fixed.

I've also explained about it in this release note and included a video showing how easy it is to reproduce this problem:
https://github.com/HotCakeX/Harden-Windows-Security/releases/tag/Hardening-Module-v.0.6.4

**Comment by HotCakeX** [comment]
Just wanted to give you an update. The issue has been fixed in Windows 11 24H2 build 26100.2448

More info here: https://blogs.windows.com/windows-insider/2024/11/14/releasing-windows-11-build-26100-2448-to-the-release-preview-channel/

**Comment by HotCakeX** [comment]
This is now in preview phase in stable builds
https://support.microsoft.com/en-us/topic/november-21-2024-kb5046740-os-build-26100-2454-preview-2040f716-b719-482a-8aff-f7f02c79b147

so if the toggle is on, you will receive it

![image](https://github.com/user-attachments/assets/712d0756-5990-43e9-91d3-762b4515e2f4)

**Comment by markuslosco** [comment]
Thanks for sharing.. very helpfull.. Here the direct links https://www.catalog.update.microsoft.com/Search.aspx?q=KB5046740

**Comment by HotCakeX** [comment]
@markuslosco Thank you ^^

**Comment by markuslosco** [comment]
As a short feedback - we have now tried to install KB5046740 on three new installed AVDs. On all three AVD's the installation ended with an error 0x800f0991. Is there already a solution to this problem?

**Comment by HotCakeX** [comment]
> As a short feedback - we have now tried to install KB5046740 on three new installed AVDs. On all three AVD's the installation ended with an error 0x800f0991. Is there already a solution to this problem?

Have you followed this exactly as explained?
https://support.microsoft.com/en-us/topic/november-21-2024-kb5046740-os-build-26100-2454-preview-2040f716-b719-482a-8aff-f7f02c79b147#ID0ENBD=Catalog

If you're going the manual route, there are 2 files that need to be downloaded and they have to be installed in order

![image](https://github.com/user-attachments/assets/b933697e-d996-43f9-8041-0ab3700daab9)

<br>

![image](https://github.com/user-attachments/assets/d26d9637-8a47-415a-881f-b0c0acb73885)

<br>

I just enabled the toggle button and received the update, i didn't use the manual method.

**Comment by markuslosco** [comment]
Yes two files correct.. the first part looks good but the second (KB5046740) is not possible to install..

**Comment by HotCakeX** [comment]
@markuslosco I think you'll have to wait for it to hit the full deployment phase then. The error in Harden Windows Security only happens when Internet Explorer mode is removed but system is not restarted afterward. So you can work around the issue by restarting the system after IE mode removal.

**Comment by HotCakeX** [comment]
The update that includes the fix for this problem is now available for everyone. 
https://x.com/WindowsUpdate/status/1866545942087815480
