### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by markuslosco** [HotCakeX/Harden-Windows-Security#421]
### Tools category

Harden Windows Security Module

### Does Your System Meet The Requirements?

- [X] Yes, I acknowledge that I've read the requirements and my system meets them. 👍

### Is your Windows Installation Genuine?

- [X] Yes, I acknowledge that the installation media of the Windows OS I used the tool on was downloaded from the official Microsoft website and I didn't tamper or modify it. 💯

### Did You Read The Frequently Asked Questions?

- [X] Yes, I've referred to the [FAQs](https://github.com/HotCakeX/Harden-Windows-Security/wiki/Answers-to-the-Basic-Frequently-Asked-Questions) and my issue is not covered/explained in there.

### Please Explain The Bug

Confirm-SystemCompliance or Confirm-SystemCompliance -offline ends with error 
![image](https://github.com/user-attachments/assets/861a545e-027c-4dbb-8499-b669135cbb9a)

regardless of whether a system/user proxy is set. Error also occurs although set-executionpolicy is set to remotesigned

### Error Details

```console
Get-Error
PS C:\Users\LAU_CLN-AVD-PAW> Get-Error

Exception             :
    Type           : System.Management.Automation.MethodInvocationException
    ErrorRecord    :
        Exception             :
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : Exception calling "Invoke" with "1" argument(s): "One or more errors occurred. (PowerShell
script execution failed: Error: Element not found.
                      Category: NotSpecified
Target:
Script StackTrace:
Exception Type: System.Management.Automation.RemoteException
StackTrace: )"
            HResult : -2146233087
        CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
        FullyQualifiedErrorId : AggregateException
        InvocationInfo        :
            ScriptLineNumber : 149
            OffsetInLine     : 13
            HistoryId        : 2
            ScriptName       : C:\Program
Files\WindowsPowerShell\Modules\Harden-Windows-Security-Module\0.6.9\Core\Confirm-SystemCompliance.psm1
            Line             : [HardenWindowsSecurity.InvokeConfirmation]::Invoke($Categories)

            Statement        : [HardenWindowsSecurity.InvokeConfirmation]::Invoke($Categories)
            PositionMessage  : At C:\Program
Files\WindowsPowerShell\Modules\Harden-Windows-Security-Module\0.6.9\Core\Confirm-SystemCompliance.psm1:149 char:13
                               +             [HardenWindowsSecurity.InvokeConfirmation]::Invoke($Categ …
                               +             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            PSScriptRoot     : C:\Program Files\WindowsPowerShell\Modules\Harden-Windows-Security-Module\0.6.9\Core
            PSCommandPath    : C:\Program
Files\WindowsPowerShell\Modules\Harden-Windows-Security-Module\0.6.9\Core\Confirm-SystemCompliance.psm1
            CommandOrigin    : Internal
        ScriptStackTrace      : at Confirm-SystemCompliance<Process>, C:\Program
Files\WindowsPowerShell\Modules\Harden-Windows-Security-Module\0.6.9\Core\Confirm-SystemCompliance.psm1: line 149
                                at <ScriptBlock>, <No file>: line 1
    TargetSite     :
        Name          : CheckActionPreference
        DeclaringType : [System.Management.Automation.ExceptionHandlingOps]
        MemberType    : Method
        Module        : System.Management.Automation.dll
    Message        : Exception calling "Invoke" with "1" argument(s): "One or more errors occurred. (PowerShell script
execution failed: Error: Element not found.
                     Category: NotSpecified
Target:
Script StackTrace:
Exception Type: System.Management.Automation.RemoteException
StackTrace: )"
    Data           : System.Collections.ListDictionaryInternal
    InnerException :
        Type            : System.AggregateException
        InnerExceptions :
            Type                        : System.Management.Automation.CmdletInvocationException
            ErrorRecord                 :
                Exception             :
                    Type       : System.InvalidOperationException
                    TargetSite :
                        Name          : <ExecuteScript>b__3
                        DeclaringType : [HardenWindowsSecurity.PowerShellExecutor+<>c__DisplayClass0_0]
                        MemberType    : Method
                        Module        : 25ortcdz.osd.dll
                    Message    : PowerShell script execution failed: Error: Element not found.
                                 Category: NotSpecified
Target:
Script StackTrace:
Exception Type: System.Management.Automation.RemoteException
StackTrace:
                    Source     : 25ortcdz.osd
                    HResult    : -2146233079
                    StackTrace :
   at HardenWindowsSecurity.PowerShellExecutor.<>c__DisplayClass0_0.<ExecuteScript>b__3(Object sender,
DataAddedEventArgs args)
   at System.Management.Automation.PSDataCollection`1.RaiseEvents(Guid psInstanceId, Int32 index)
   at System.Management.Automation.PSDataCollection`1.InternalAddRange(Guid psInstanceId, ICollection collection)
   at System.Management.Automation.Internal.PSDataCollectionStream`1.Write(Object obj, Boolean enumerateCollection)
   at System.Management.Automation.Internal.Pipe.AddToPipe(Object obj)
   at System.Management.Automation.MshCommandRuntime._WriteErrorSkipAllowCheck(ErrorRecord errorRecord, Nullable`1
actionPreference, Boolean isFromNativeStdError)
   at System.Management.Automation.MshCommandRuntime.DoWriteError(Object obj)
   at System.Management.Automation.MshCommandRuntime.WriteError(ErrorRecord errorRecord, Boolean overrideInquire)
   at Microsoft.PowerShell.Commands.InvokeCommandCommand.WriteStreamObjectsFromCollection(IEnumerable`1 results)
   at Microsoft.PowerShell.Commands.InvokeCommandCommand.WriteJobResults(Boolean nonblocking)
   at Microsoft.PowerShell.Commands.InvokeCommandCommand.EndProcessing()
   at System.Management.Automation.CommandProcessorBase.Complete()
                CategoryInfo          : NotSpecified: (:) [Invoke-Command], InvalidOperationException
                FullyQualifiedErrorId :
System.InvalidOperationException,Microsoft.PowerShell.Commands.InvokeCommandCommand
                InvocationInfo        :
                    MyCommand        : Invoke-Command
                    ScriptLineNumber : 3
                    OffsetInLine     : 8
                    HistoryId        : 1
                    Line             : return ((Get-WindowsCapability -Online | Where-Object -FilterScript { $_.Name
-like "*$CompatibilityName*" }).State)
                    Statement        : ((Get-WindowsCapability -Online | Where-Object -FilterScript { $_.Name -like
"*$CompatibilityName*" }).State)
                    PositionMessage  : At line:3 char:8
                                       + return ((Get-WindowsCapability -Online | Where-Object -FilterScript { …
                                       +        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                    InvocationName   : Get-WindowsCapability
                    CommandOrigin    : Internal
                ScriptStackTrace      : at <ScriptBlock><End>, C:\Users\LAU_CLN-AVD-PAW\AppData\Local\Temp\remoteIpMoPr
oxy_DISM_3.0_localhost_c6acf2c4-1b01-461a-8439-437efa8ba158\remoteIpMoProxy_DISM_3.0_localhost_c6acf2c4-1b01-461a-8439-
437efa8ba158.psm1: line 3307
                                        at <ScriptBlock>, <No file>: line 3
                PipelineIterationInfo :
                                      0
                                      1
            WasThrownFromThrowStatement : True
            TargetSite                  :
                Name          : Invoke
                DeclaringType : [System.Management.Automation.Runspaces.PipelineBase]
                MemberType    : Method
                Module        : System.Management.Automation.dll
            Message                     : PowerShell script execution failed: Error: Element not found.
                                          Category: NotSpecified
Target:
Script StackTrace:
Exception Type: System.Management.Automation.RemoteException
StackTrace:
            Data                        : System.Collections.ListDictionaryInternal
            InnerException              :
                Type       : System.InvalidOperationException
                TargetSite :
                    Name          : <ExecuteScript>b__3
                    DeclaringType : [HardenWindowsSecurity.PowerShellExecutor+<>c__DisplayClass0_0]
                    MemberType    : Method
                    Module        : 25ortcdz.osd.dll
                Message    : PowerShell script execution failed: Error: Element not found.
                             Category: NotSpecified
Target:
Script StackTrace:
Exception Type: System.Management.Automation.RemoteException
StackTrace:
                Source     : 25ortcdz.osd
                HResult    : -2146233079
                StackTrace :
   at HardenWindowsSecurity.PowerShellExecutor.<>c__DisplayClass0_0.<ExecuteScript>b__3(Object sender,
DataAddedEventArgs args)
   at System.Management.Automation.PSDataCollection`1.RaiseEvents(Guid psInstanceId, Int32 index)
   at System.Management.Automation.PSDataCollection`1.InternalAddRange(Guid psInstanceId, ICollection collection)
   at System.Management.Automation.Internal.PSDataCollectionStream`1.Write(Object obj, Boolean enumerateCollection)
   at System.Management.Automation.Internal.Pipe.AddToPipe(Object obj)
   at System.Management.Automation.MshCommandRuntime._WriteErrorSkipAllowCheck(ErrorRecord errorRecord, Nullable`1
actionPreference, Boolean isFromNativeStdError)
   at System.Management.Automation.MshCommandRuntime.DoWriteError(Object obj)
   at System.Management.Automation.MshCommandRuntime.WriteError(ErrorRecord errorRecord, Boolean overrideInquire)
   at Microsoft.PowerShell.Commands.InvokeCommandCommand.WriteStreamObjectsFromCollection(IEnumerable`1 results)
   at Microsoft.PowerShell.Commands.InvokeCommandCommand.WriteJobResults(Boolean nonblocking)
   at Microsoft.PowerShell.Commands.InvokeCommandCommand.EndProcessing()
   at System.Management.Automation.CommandProcessorBase.Complete()
            Source                      : System.Management.Automation
            HResult                     : -2146233087
            StackTrace                  :
   at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
   at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
   at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
   at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input,
PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1
output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.Invoke[T]()
   at HardenWindowsSecurity.PowerShellExecutor.ExecuteScript(String script, Boolean returnOutput, Boolean
NonTerminatingErrors)
   at HardenWindowsSecurity.WindowsFeatureChecker.GetCapabilityState(String capabilityName)
   at HardenWindowsSecurity.WindowsFeatureChecker.CheckWindowsFeatures()
   at HardenWindowsSecurity.ConfirmSystemComplianceMethods.<>c.<VerifyOptionalWindowsFeatures>b__13_0()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext
executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext
executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at HardenWindowsSecurity.ConfirmSystemComplianceMethods.RunComplianceMethodsInParallelAsync(String[] methodNames)
        Message         : One or more errors occurred. (PowerShell script execution failed: Error: Element not found.
                          Category: NotSpecified
Target:
Script StackTrace:
Exception Type: System.Management.Automation.RemoteException
StackTrace: )
        TargetSite      :
            Name          : OrchestrateComplianceChecks
            DeclaringType : [HardenWindowsSecurity.ConfirmSystemComplianceMethods]
            MemberType    : Method
            Module        : 25ortcdz.osd.dll
        InnerException  :
            Type                        : System.Management.Automation.CmdletInvocationException
            ErrorRecord                 :
                Exception             :
                    Type       : System.InvalidOperationException
                    TargetSite :
                        Name          : <ExecuteScript>b__3
                        DeclaringType : [HardenWindowsSecurity.PowerShellExecutor+<>c__DisplayClass0_0]
                        MemberType    : Method
                        Module        : 25ortcdz.osd.dll
                    Message    : PowerShell script execution failed: Error: Element not found.
                                 Category: NotSpecified
Target:
Script StackTrace:
Exception Type: System.Management.Automation.RemoteException
StackTrace:
                    Source     : 25ortcdz.osd
                    HResult    : -2146233079
                    StackTrace :
   at HardenWindowsSecurity.PowerShellExecutor.<>c__DisplayClass0_0.<ExecuteScript>b__3(Object sender,
DataAddedEventArgs args)
   at System.Management.Automation.PSDataCollection`1.RaiseEvents(Guid psInstanceId, Int32 index)
   at System.Management.Automation.PSDataCollection`1.InternalAddRange(Guid psInstanceId, ICollection collection)
   at System.Management.Automation.Internal.PSDataCollectionStream`1.Write(Object obj, Boolean enumerateCollection)
   at System.Management.Automation.Internal.Pipe.AddToPipe(Object obj)
   at System.Management.Automation.MshCommandRuntime._WriteErrorSkipAllowCheck(ErrorRecord errorRecord, Nullable`1
actionPreference, Boolean isFromNativeStdError)
   at System.Management.Automation.MshCommandRuntime.DoWriteError(Object obj)
   at System.Management.Automation.MshCommandRuntime.WriteError(ErrorRecord errorRecord, Boolean overrideInquire)
   at Microsoft.PowerShell.Commands.InvokeCommandCommand.WriteStreamObjectsFromCollection(IEnumerable`1 results)
   at Microsoft.PowerShell.Commands.InvokeCommandCommand.WriteJobResults(Boolean nonblocking)
   at Microsoft.PowerShell.Commands.InvokeCommandCommand.EndProcessing()
   at System.Management.Automation.CommandProcessorBase.Complete()
                CategoryInfo          : NotSpecified: (:) [Invoke-Command], InvalidOperationException
                FullyQualifiedErrorId :
System.InvalidOperationException,Microsoft.PowerShell.Commands.InvokeCommandCommand
                InvocationInfo        :
                    MyCommand        : Invoke-Command
                    ScriptLineNumber : 3
                    OffsetInLine     : 8
                    HistoryId        : 1
                    Line             : return ((Get-WindowsCapability -Online | Where-Object -FilterScript { $_.Name
-like "*$CompatibilityName*" }).State)
                    Statement        : ((Get-WindowsCapability -Online | Where-Object -FilterScript { $_.Name -like
"*$CompatibilityName*" }).State)
                    PositionMessage  : At line:3 char:8
                                       + return ((Get-WindowsCapability -Online | Where-Object -FilterScript { …
                                       +        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                    InvocationName   : Get-WindowsCapability
                    CommandOrigin    : Internal
                ScriptStackTrace      : at <ScriptBlock><End>, C:\Users\LAU_CLN-AVD-PAW\AppData\Local\Temp\remoteIpMoPr
oxy_DISM_3.0_localhost_c6acf2c4-1b01-461a-8439-437efa8ba158\remoteIpMoProxy_DISM_3.0_localhost_c6acf2c4-1b01-461a-8439-
437efa8ba158.psm1: line 3307
                                        at <ScriptBlock>, <No file>: line 3
                PipelineIterationInfo :
                                      0
                                      1
            WasThrownFromThrowStatement : True
            TargetSite                  :
                Name          : Invoke
                DeclaringType : [System.Management.Automation.Runspaces.PipelineBase]
                MemberType    : Method
                Module        : System.Management.Automation.dll
            Message                     : PowerShell script execution failed: Error: Element not found.
                                          Category: NotSpecified
Target:
Script StackTrace:
Exception Type: System.Management.Automation.RemoteException
StackTrace:
            Data                        : System.Collections.ListDictionaryInternal
            InnerException              :
                Type       : System.InvalidOperationException
                TargetSite :
                    Name          : <ExecuteScript>b__3
                    DeclaringType : [HardenWindowsSecurity.PowerShellExecutor+<>c__DisplayClass0_0]
                    MemberType    : Method
                    Module        : 25ortcdz.osd.dll
                Message    : PowerShell script execution failed: Error: Element not found.
                             Category: NotSpecified
Target:
Script StackTrace:
Exception Type: System.Management.Automation.RemoteException
StackTrace:
                Source     : 25ortcdz.osd
                HResult    : -2146233079
                StackTrace :
   at HardenWindowsSecurity.PowerShellExecutor.<>c__DisplayClass0_0.<ExecuteScript>b__3(Object sender,
DataAddedEventArgs args)
   at System.Management.Automation.PSDataCollection`1.RaiseEvents(Guid psInstanceId, Int32 index)
   at System.Management.Automation.PSDataCollection`1.InternalAddRange(Guid psInstanceId, ICollection collection)
   at System.Management.Automation.Internal.PSDataCollectionStream`1.Write(Object obj, Boolean enumerateCollection)
   at System.Management.Automation.Internal.Pipe.AddToPipe(Object obj)
   at System.Management.Automation.MshCommandRuntime._WriteErrorSkipAllowCheck(ErrorRecord errorRecord, Nullable`1
actionPreference, Boolean isFromNativeStdError)
   at System.Management.Automation.MshCommandRuntime.DoWriteError(Object obj)
   at System.Management.Automation.MshCommandRuntime.WriteError(ErrorRecord errorRecord, Boolean overrideInquire)
   at Microsoft.PowerShell.Commands.InvokeCommandCommand.WriteStreamObjectsFromCollection(IEnumerable`1 results)
   at Microsoft.PowerShell.Commands.InvokeCommandCommand.WriteJobResults(Boolean nonblocking)
   at Microsoft.PowerShell.Commands.InvokeCommandCommand.EndProcessing()
   at System.Management.Automation.CommandProcessorBase.Complete()
            Source                      : System.Management.Automation
            HResult                     : -2146233087
            StackTrace                  :
   at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
   at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
   at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
   at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input,
PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1
output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.Invoke[T]()
   at HardenWindowsSecurity.PowerShellExecutor.ExecuteScript(String script, Boolean returnOutput, Boolean
NonTerminatingErrors)
   at HardenWindowsSecurity.WindowsFeatureChecker.GetCapabilityState(String capabilityName)
   at HardenWindowsSecurity.WindowsFeatureChecker.CheckWindowsFeatures()
   at HardenWindowsSecurity.ConfirmSystemComplianceMethods.<>c.<VerifyOptionalWindowsFeatures>b__13_0()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext
executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext
executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at HardenWindowsSecurity.ConfirmSystemComplianceMethods.RunComplianceMethodsInParallelAsync(String[] methodNames)
        Source          : 25ortcdz.osd
        HResult         : -2146233088
        StackTrace      :
   at HardenWindowsSecurity.ConfirmSystemComplianceMethods.OrchestrateComplianceChecks(String[] methodNames)
   at HardenWindowsSecurity.InvokeConfirmation.Invoke(String[] Categories)
   at CallSite.Target(Closure, CallSite, Type, Object)
    Source         : System.Management.Automation
    HResult        : -2146233087
    StackTrace     :
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception
exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object
inputToProcess)
   at System.Management.Automation.PSScriptCmdlet.DoProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
FullyQualifiedErrorId : AggregateException
InvocationInfo        :
    ScriptLineNumber : 149
    OffsetInLine     : 13
    HistoryId        : 2
    ScriptName       : C:\Program
Files\WindowsPowerShell\Modules\Harden-Windows-Security-Module\0.6.9\Core\Confirm-SystemCompliance.psm1
    Line             : [HardenWindowsSecurity.InvokeConfirmation]::Invoke($Categories)

    Statement        : [HardenWindowsSecurity.InvokeConfirmation]::Invoke($Categories)
    PositionMessage  : At C:\Program
Files\WindowsPowerShell\Modules\Harden-Windows-Security-Module\0.6.9\Core\Confirm-SystemCompliance.psm1:149 char:13
                       +             [HardenWindowsSecurity.InvokeConfirmation]::Invoke($Categ …
                       +             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    PSScriptRoot     : C:\Program Files\WindowsPowerShell\Modules\Harden-Windows-Security-Module\0.6.9\Core
    PSCommandPath    : C:\Program
Files\WindowsPowerShell\Modules\Harden-Windows-Security-Module\0.6.9\Core\Confirm-SystemCompliance.psm1
    CommandOrigin    : Internal
ScriptStackTrace      : at Confirm-SystemCompliance<Process>, C:\Program
Files\WindowsPowerShell\Modules\Harden-Windows-Security-Module\0.6.9\Core\Confirm-SystemCompliance.psm1: line 149
                        at <ScriptBlock>, <No file>: line 1
```

**Comment by HotCakeX** [comment]
Hi, it's an issue in Windows 11 24H2, it has been fixed but the fix is still being rolled out to users. You can enable this toggle to receive it faster.

More info in this thread:

https://github.com/HotCakeX/Harden-Windows-Security/issues/368

<br>

<img width="833" alt="image" src="https://github.com/user-attachments/assets/5516d140-4e97-423a-8f2d-03818dcf55ae">
