### ISSUE TITLE
MethodInvocationException: Exception calling "Run" with "1" argument(s): "Could not relaunch PowerShell after update.

### ISSUE THREAD

**Issue by lsiem** [HotCakeX/Harden-Windows-Security#431]
### Tools category

Harden Windows Security Module

### Does Your System Meet The Requirements?

- [X] Yes, I acknowledge that I've read the requirements and my system meets them. 👍

### Is your Windows Installation Genuine?

- [X] Yes, I acknowledge that the installation media of the Windows OS I used the tool on was downloaded from the official Microsoft website and I didn't tamper or modify it. 💯

### Did You Read The Frequently Asked Questions?

- [X] Yes, I've referred to the [FAQs](https://github.com/HotCakeX/Harden-Windows-Security/wiki/Answers-to-the-Basic-Frequently-Asked-Questions) and my issue is not covered/explained in there.

### Please Explain The Bug

When executing the script `(irm 'https://raw.githubusercontent.com/HotCakeX/Harden-Windows-Security/main/Harden-Windows-Security.ps1')+'P'|iex`, I encountered the following error:
 `"30/11/2024 08:45:46: Could not find UserName or FullName of the current user with the SID S-1-12-1-2513377144-1106595059-296177290-3867577271." `

Despite this, the GUI opens, and everything seems to function properly. I selected the "Recommended" preset and clicked the "Run" button, but the error in the Error Details occurs.

### Error Details

```console
MethodInvocationException: Exception calling "Run" with "1" argument(s): "Could not relaunch PowerShell after update. Please close and reopen
PowerShell to run your command again."


ErrorRecord                 : Exception calling "Run" with "1" argument(s): "Could not relaunch PowerShell after
                              update. Please close and reopen PowerShell to run your command again."
WasThrownFromThrowStatement : False
TargetSite                  : Void CheckActionPreference(System.Management.Automation.Language.FunctionContext,
                              System.Exception)
Message                     : Exception calling "Run" with "1" argument(s): "Could not relaunch PowerShell after
                              update. Please close and reopen PowerShell to run your command again."
Data                        : {[System.Management.Automation.Interpreter.InterpretedFrameInfo,
                              System.Management.Automation.Interpreter.InterpretedFrameInfo[]]}
InnerException              : System.Management.Automation.RuntimeException: Could not relaunch PowerShell after
                              update. Please close and reopen PowerShell to run your command again.
                               ---> System.Management.Automation.RuntimeException: Could not relaunch PowerShell after
                              update. Please close and reopen PowerShell to run your command again.
                                 --- End of inner exception stack trace ---
                                 at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
                                 at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace
                              rs, Boolean performSyncInvoke)
                                 at
                              System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace
                              rsToUse, Boolean isSync)
                                 at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataColl
                              ection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
                                 at
                              System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1
                              input, PSDataCollection`1 output, PSInvocationSettings settings)
                                 at System.Management.Automation.PowerShell.Invoke()
                                 at HardenWindowsSecurity.PowerShellExecutor.ExecuteScript(String script, Boolean
                              returnOutput, Boolean NonTerminatingErrors)
                                 at HardenWindowsSecurity.DownloadsDefenseMeasures.Invoke()
                                 at HardenWindowsSecurity.GUIProtectWinSecurity.<>c.<AddEventHandlers>b__0_17()
                                 at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread
                              threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object
                              state)
                              --- End of stack trace from previous location ---
                                 at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread
                              threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object
                              state)
                                 at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread
                              threadPoolThread)
                              --- End of stack trace from previous location ---
                                 at
                              HardenWindowsSecurity.GUIProtectWinSecurity.<>c.<<AddEventHandlers>b__0_10>d.MoveNext()
                              --- End of stack trace from previous location ---
                                 at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
                                 at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback,
                              Object args, Int32 numArgs)
                                 at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate
                              callback, Object args, Int32 numArgs, Delegate catchHandler)
                                 at System.Windows.Threading.DispatcherOperation.InvokeImpl()
                                 at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
                                 at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext,
                              ContextCallback callback, Object state)
                              --- End of stack trace from previous location ---
                                 at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext,
                              ContextCallback callback, Object state)
                                 at
                              MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext
                              executionContext, ContextCallback callback, Object state)
                                 at System.Windows.Threading.DispatcherOperation.Invoke()
                                 at System.Windows.Threading.Dispatcher.ProcessQueue()
                                 at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr
                              wParam, IntPtr lParam, Boolean& handled)
                                 at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback,
                              Object args, Int32 numArgs)
                                 at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate
                              callback, Object args, Int32 numArgs, Delegate catchHandler)
                                 at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority,
                              TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
                                 at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam,
                              IntPtr lParam)
                                 at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
                                 at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
                                 at System.Windows.Application.RunDispatcher(Object ignore)
                                 at System.Windows.Application.RunInternal(Window window)
                                 at CallSite.Target(Closure, CallSite, Application, Window)
HelpLink                    :
Source                      : System.Management.Automation
HResult                     : -2146233087
StackTrace                  :    at
                              System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext
                              funcContext, Exception exception)
                                 at
                              System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame
                              frame)
                                 at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(Interp
                              retedFrame frame)
                                 at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(Interp
                              retedFrame frame)

MyCommand             :
BoundParameters       : {}
UnboundArguments      : {}
ScriptLineNumber      : 325
OffsetInLine          : 17
HistoryId             : 1
ScriptName            : C:\Users\LasseSiemoneit\OneDrive - Lasse Siemoneit\Documents\PowerShell\Modules\Harden-Windows-
                        Security-Module\0.6.9\Core\Protect-WindowsSecurity.psm1
Line                  :                 [System.Void]
                        [HardenWindowsSecurity.GUIMain]::app.Run([HardenWindowsSecurity.GUIMain]::mainGUIWindow)

Statement             : [System.Void]
                        [HardenWindowsSecurity.GUIMain]::app.Run([HardenWindowsSecurity.GUIMain]::mainGUIWindow)
PositionMessage       : At C:\Users\LasseSiemoneit\OneDrive - Lasse Siemoneit\Documents\PowerShell\Modules\Harden-Windo
                        ws-Security-Module\0.6.9\Core\Protect-WindowsSecurity.psm1:325 char:17
                        + …             [System.Void] [HardenWindowsSecurity.GUIMain]::app.Run([H …
                        +               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PSScriptRoot          : C:\Users\LasseSiemoneit\OneDrive - Lasse
                        Siemoneit\Documents\PowerShell\Modules\Harden-Windows-Security-Module\0.6.9\Core
PSCommandPath         : C:\Users\LasseSiemoneit\OneDrive - Lasse Siemoneit\Documents\PowerShell\Modules\Harden-Windows-
                        Security-Module\0.6.9\Core\Protect-WindowsSecurity.psm1
InvocationName        :
PipelineLength        : 0
PipelinePosition      : 0
ExpectingInput        : False
CommandOrigin         : Internal
DisplayScriptPosition :
```

**Comment by HotCakeX** [comment]
Which OS are you using and what kind of user account do you have?

**Comment by HotCakeX** [comment]
I need a lot more information to be able to help.

When SID can't be resolved for any reason, no error is thrown, instead a simple message is logged on the console.

i don't know why your SID starts with `S-1-12-1-`, i couldn't find any reference to SID that starts with that prefix. The way the SID and username is retrieved is standard procedure.

The error you're getting is not about SID though, your system is failing at this part

```powershell
pwsh.exe -NoProfile -NoLogo -NoExit
```

Which is weird because there is nothing wrong with that. I know you checked the boxes up there but are you sure you're using genuine untampered OS? Didn't use any 3rd party tools like rufus to tamper with OS installation etc.? because there is something wrong on your end and this issue doesn't seem to be normal, and since i have 0 information about your system i'm not able to help much.
