### ISSUE TITLE
[Bug]: MSFT_MpPreference error after installation

### ISSUE THREAD

**Issue by hardwarebxl** [HotCakeX/Harden-Windows-Security#440]
### Tools category

Harden Windows Security Module

### Does Your System Meet The Requirements?

- [X] Yes, I acknowledge that I've read the requirements and my system meets them. 👍

### Is your Windows Installation Genuine?

- [X] Yes, I acknowledge that the installation media of the Windows OS I used the tool on was downloaded from the official Microsoft website and I didn't tamper or modify it. 💯

### Did You Read The Frequently Asked Questions?

- [X] Yes, I've referred to the [FAQs](https://github.com/HotCakeX/Harden-Windows-Security/wiki/Answers-to-the-Basic-Frequently-Asked-Questions) and my issue is not covered/explained in there.

### Please Explain The Bug

Error after installation right now with current version..

### Error Details

```console
PowerShell 7.4.6
PS C:\Users\Fred> Install-Module -Name 'Harden-Windows-Security-Module' -Force
PS C:\Users\Fred> Protect-WindowsSecurity -GUI
Protect-WindowsSecurity: Exception calling "Initialize" with "1" argument(s): "WMI query for 'MSFT_MpPreference' failed: Generic failure "
PS C:\Users\Fred> Get-Error

Exception             :
    Type           : System.Management.Automation.MethodInvocationException
    ErrorRecord    :
        Exception             :
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : Exception calling "Initialize" with "1" argument(s): "WMI query for 'MSFT_MpPreference' failed:
Generic failure "
            HResult : -2146233087
        CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
        FullyQualifiedErrorId : PowerShellExecutionException
        InvocationInfo        :
            ScriptLineNumber : 275
            OffsetInLine     : 9
            HistoryId        : 2
            ScriptName       :
C:\Users\Fred\Documents\PowerShell\Modules\Harden-Windows-Security-Module\0.6.9\Core\Protect-WindowsSecurity.psm1
            Line             : [HardenWindowsSecurity.Initializer]::Initialize($VerbosePreference)

            Statement        : [HardenWindowsSecurity.Initializer]::Initialize($VerbosePreference)
            PositionMessage  : At
C:\Users\Fred\Documents\PowerShell\Modules\Harden-Windows-Security-Module\0.6.9\Core\Protect-WindowsSecurity.psm1:275
char:9
                               +         [HardenWindowsSecurity.Initializer]::Initialize($VerbosePrefe …
                               +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            PSScriptRoot     : C:\Users\Fred\Documents\PowerShell\Modules\Harden-Windows-Security-Module\0.6.9\Core
            PSCommandPath    :
C:\Users\Fred\Documents\PowerShell\Modules\Harden-Windows-Security-Module\0.6.9\Core\Protect-WindowsSecurity.psm1
            CommandOrigin    : Internal
        ScriptStackTrace      : at Protect-WindowsSecurity<Begin>,
C:\Users\Fred\Documents\PowerShell\Modules\Harden-Windows-Security-Module\0.6.9\Core\Protect-WindowsSecurity.psm1:
line 275
                                at <ScriptBlock>, <No file>: line 1
    TargetSite     :
        Name          : CheckActionPreference
        DeclaringType : [System.Management.Automation.ExceptionHandlingOps]
        MemberType    : Method
        Module        : System.Management.Automation.dll
    Message        : Exception calling "Initialize" with "1" argument(s): "WMI query for 'MSFT_MpPreference' failed:
Generic failure "
    Data           : System.Collections.ListDictionaryInternal
    InnerException :
        Type           : HardenWindowsSecurity.PowerShellExecutionException
        TargetSite     :
            Name          : GetMpPreference
            DeclaringType : [HardenWindowsSecurity.MpPreferenceHelper]
            MemberType    : Method
            Module        : h2fzomw2.gm0.dll
        Message        : WMI query for 'MSFT_MpPreference' failed: Generic failure
        InnerException :
            Type             : System.Management.ManagementException
            ErrorInformation : System.Management.ManagementBaseObject
            ErrorCode        : Failed
            TargetSite       :
                Name          : ThrowWithExtendedInfo
                DeclaringType : [System.Management.ManagementException]
                MemberType    : Method
                Module        : System.Management.dll
            Message          : Generic failure
            Source           : System.Management
            HResult          : -2146233087
            StackTrace       :
   at System.Management.ManagementException.ThrowWithExtendedInfo(ManagementStatus errorCode)
   at System.Management.ManagementObjectCollection.ManagementObjectEnumerator.MoveNext()
   at System.Management.ManagementObjectCollection.get_Count()
   at HardenWindowsSecurity.MpPreferenceHelper.GetMpPreference()
        Source         : h2fzomw2.gm0
        HResult        : -2146233088
        StackTrace     :
   at HardenWindowsSecurity.MpPreferenceHelper.GetMpPreference()
   at HardenWindowsSecurity.Initializer.Initialize(String VerbosePreference, Boolean IsConfirmationDuringRunTime)
   at CallSite.Target(Closure, CallSite, Type, Object)
    Source         : System.Management.Automation
    HResult        : -2146233087
    StackTrace     :
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception
exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object
inputToProcess)
   at System.Management.Automation.Cmdlet.DoBeginProcessing()
   at System.Management.Automation.CommandProcessorBase.DoBegin()
CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
FullyQualifiedErrorId : PowerShellExecutionException
InvocationInfo        :
    ScriptLineNumber : 275
    OffsetInLine     : 9
    HistoryId        : 2
    ScriptName       :
C:\Users\Fred\Documents\PowerShell\Modules\Harden-Windows-Security-Module\0.6.9\Core\Protect-WindowsSecurity.psm1
    Line             : [HardenWindowsSecurity.Initializer]::Initialize($VerbosePreference)

    Statement        : [HardenWindowsSecurity.Initializer]::Initialize($VerbosePreference)
    PositionMessage  : At
C:\Users\Fred\Documents\PowerShell\Modules\Harden-Windows-Security-Module\0.6.9\Core\Protect-WindowsSecurity.psm1:275
char:9
                       +         [HardenWindowsSecurity.Initializer]::Initialize($VerbosePrefe …
                       +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    PSScriptRoot     : C:\Users\Fred\Documents\PowerShell\Modules\Harden-Windows-Security-Module\0.6.9\Core
    PSCommandPath    :
C:\Users\Fred\Documents\PowerShell\Modules\Harden-Windows-Security-Module\0.6.9\Core\Protect-WindowsSecurity.psm1
    CommandOrigin    : Internal
ScriptStackTrace      : at Protect-WindowsSecurity<Begin>,
C:\Users\Fred\Documents\PowerShell\Modules\Harden-Windows-Security-Module\0.6.9\Core\Protect-WindowsSecurity.psm1:
line 275
                        at <ScriptBlock>, <No file>: line 1

PS C:\Users\Fred>
```

**Comment by HotCakeX** [comment]
It's not related to the module or my code.

```
"WMI query for 'MSFT_MpPreference' failed: Generic failure "
```

it's saying your system is not allowing Defender preferences to be queried using WMI which is a very standard procedure.

`Generic failure` suggests the problem is on your end.

I haven't touched that part of the code in months, so it's not something that has changed recently. The last version for Harden Windows Security module was over 1 month ago.

I suggest reading the FAQ document, especially about 3rd party AVs section: https://github.com/HotCakeX/Harden-Windows-Security/wiki/Answers-to-the-Basic-Frequently-Asked-Questions
