### ISSUE TITLE
[Bug]: Harden Windows Security Module crashes on ARM Windows VM

### ISSUE THREAD

**Issue by ghost** [HotCakeX/Harden-Windows-Security#443]
### Tools category

Harden Windows Security Module

### Does Your System Meet The Requirements?

- [X] Yes, I acknowledge that I've read the requirements and my system meets them. 👍

### Is your Windows Installation Genuine?

- [X] Yes, I acknowledge that the installation media of the Windows OS I used the tool on was downloaded from the official Microsoft website and I didn't tamper or modify it. 💯

### Did You Read The Frequently Asked Questions?

- [X] Yes, I've referred to the [FAQs](https://github.com/HotCakeX/Harden-Windows-Security/wiki/Answers-to-the-Basic-Frequently-Asked-Questions) and my issue is not covered/explained in there.

### Please Explain The Bug

Harden Windows Security app crashed when I was running `Confirm and Verify`. I am using an official ARM Windows 11 24H2 ISO on a UTM Virtual Machine on macOS.

### Error Details

```console
MethodInvocationException: Exception calling "Run" with "1" argument(s): "One or more errors occurred. (PowerShell script execution failed: Error:
Element not found.  Category: NotSpecified Target:  Script StackTrace:  Exception Type:
System.Management.Automation.RemoteException StackTrace: )"


ErrorRecord                 : Exception calling "Run" with "1" argument(s): "One or more errors occurred. (PowerShell
                              script execution failed: Error: Element not found.

                              Category: NotSpecified
                              Target:
                              Script StackTrace:
                              Exception Type: System.Management.Automation.RemoteException
                              StackTrace: )"
WasThrownFromThrowStatement : False
TargetSite                  : Void CheckActionPreference(System.Management.Automation.Language.FunctionContext,
                              System.Exception)
Message                     : Exception calling "Run" with "1" argument(s): "One or more errors occurred. (PowerShell
                              script execution failed: Error: Element not found.

                              Category: NotSpecified
                              Target:
                              Script StackTrace:
                              Exception Type: System.Management.Automation.RemoteException
                              StackTrace: )"
Data                        : {[System.Management.Automation.Interpreter.InterpretedFrameInfo,
                              System.Management.Automation.Interpreter.InterpretedFrameInfo[]]}
InnerException              : System.AggregateException: One or more errors occurred. (PowerShell script execution
                              failed: Error: Element not found.

                              Category: NotSpecified
                              Target:
                              Script StackTrace:
                              Exception Type: System.Management.Automation.RemoteException
                              StackTrace: )
                               ---> System.Management.Automation.CmdletInvocationException: PowerShell script
                              execution failed: Error: Element not found.

                              Category: NotSpecified
                              Target:
                              Script StackTrace:
                              Exception Type: System.Management.Automation.RemoteException
                              StackTrace:
                               ---> System.InvalidOperationException: PowerShell script execution failed: Error:
                              Element not found.

                              Category: NotSpecified
                              Target:
                              Script StackTrace:
                              Exception Type: System.Management.Automation.RemoteException
                              StackTrace:
                                 at
                              HardenWindowsSecurity.PowerShellExecutor.<>c__DisplayClass0_0.<ExecuteScript>b__3(Object
                              sender, DataAddedEventArgs args)
                                 at System.Management.Automation.PSDataCollection`1.RaiseEvents(Guid psInstanceId,
                              Int32 index)
                                 at System.Management.Automation.PSDataCollection`1.InternalAddRange(Guid
                              psInstanceId, ICollection collection)
                                 at System.Management.Automation.Internal.PSDataCollectionStream`1.Write(Object obj,
                              Boolean enumerateCollection)
                                 at System.Management.Automation.Internal.Pipe.AddToPipe(Object obj)
                                 at
                              System.Management.Automation.MshCommandRuntime._WriteErrorSkipAllowCheck(ErrorRecord
                              errorRecord, Nullable`1 actionPreference, Boolean isFromNativeStdError)
                                 at System.Management.Automation.MshCommandRuntime.DoWriteError(Object obj)
                                 at System.Management.Automation.MshCommandRuntime.WriteError(ErrorRecord errorRecord,
                              Boolean overrideInquire)
                                 at Microsoft.PowerShell.Commands.InvokeCommandCommand.WriteStreamObjectsFromCollection
                              (IEnumerable`1 results)
                                 at Microsoft.PowerShell.Commands.InvokeCommandCommand.WriteJobResults(Boolean
                              nonblocking)
                                 at Microsoft.PowerShell.Commands.InvokeCommandCommand.EndProcessing()
                                 at System.Management.Automation.CommandProcessorBase.Complete()
                                 --- End of inner exception stack trace ---
                                 at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
                                 at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace
                              rs, Boolean performSyncInvoke)
                                 at
                              System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace
                              rsToUse, Boolean isSync)
                                 at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataColl
                              ection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
                                 at
                              System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1
                              input, PSDataCollection`1 output, PSInvocationSettings settings)
                                 at System.Management.Automation.PowerShell.Invoke[T]()
                                 at HardenWindowsSecurity.PowerShellExecutor.ExecuteScript(String script, Boolean
                              returnOutput, Boolean NonTerminatingErrors)
                                 at HardenWindowsSecurity.WindowsFeatureChecker.GetCapabilityState(String
                              capabilityName)
                                 at HardenWindowsSecurity.WindowsFeatureChecker.CheckWindowsFeatures()
                                 at HardenWindowsSecurity.ConfirmSystemComplianceMethods.<>c.<VerifyOptionalWindowsFeat
                              ures>b__13_0()
                                 at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread
                              threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object
                              state)
                              --- End of stack trace from previous location ---
                                 at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread
                              threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object
                              state)
                                 at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread
                              threadPoolThread)
                              --- End of stack trace from previous location ---
                                 at HardenWindowsSecurity.ConfirmSystemComplianceMethods.RunComplianceMethodsInParallel
                              Async(String[] methodNames)
                                 --- End of inner exception stack trace ---
                                 at HardenWindowsSecurity.ConfirmSystemComplianceMethods.OrchestrateComplianceChecks(St
                              ring[] methodNames)
                                 at HardenWindowsSecurity.InvokeConfirmation.Invoke(String[] Categories)
                                 at
                              HardenWindowsSecurity.GUIMain.NavigationVM.<>c__DisplayClass4_0.<ConfirmView>b__10()
                                 at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread
                              threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object
                              state)
                              --- End of stack trace from previous location ---
                                 at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread
                              threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object
                              state)
                                 at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread
                              threadPoolThread)
                              --- End of stack trace from previous location ---
                                 at HardenWindowsSecurity.GUIMain.NavigationVM.<>c__DisplayClass4_0.<<ConfirmView>b__7>
                              d.MoveNext()
                              --- End of stack trace from previous location ---
                                 at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
                                 at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback,
                              Object args, Int32 numArgs)
                                 at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate
                              callback, Object args, Int32 numArgs, Delegate catchHandler)
                                 at System.Windows.Threading.DispatcherOperation.InvokeImpl()
                                 at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
                                 at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext,
                              ContextCallback callback, Object state)
                              --- End of stack trace from previous location ---
                                 at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext,
                              ContextCallback callback, Object state)
                                 at
                              MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext
                              executionContext, ContextCallback callback, Object state)
                                 at System.Windows.Threading.DispatcherOperation.Invoke()
                                 at System.Windows.Threading.Dispatcher.ProcessQueue()
                                 at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr
                              wParam, IntPtr lParam, Boolean& handled)
                                 at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam,
                              Boolean& handled)
                                 at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback,
                              Object args, Int32 numArgs)
                                 at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate
                              callback, Object args, Int32 numArgs, Delegate catchHandler)
                                 at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority,
                              TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
                                 at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam,
                              IntPtr lParam)
                                 at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
                                 at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
                                 at System.Windows.Application.RunDispatcher(Object ignore)
                                 at System.Windows.Application.RunInternal(Window window)
                                 at CallSite.Target(Closure, CallSite, Application, Window)
HelpLink                    :
Source                      : System.Management.Automation
HResult                     : -2146233087
StackTrace                  :    at
                              System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext
                              funcContext, Exception exception)
                                 at
                              System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame
                              frame)
                                 at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(Interp
                              retedFrame frame)
                                 at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(Interp
                              retedFrame frame)

MyCommand             :
BoundParameters       : {}
UnboundArguments      : {}
ScriptLineNumber      : 325
OffsetInLine          : 17
HistoryId             : 1
ScriptName            : C:\Users\use\Documents\PowerShell\Modules\Harden-Windows-Security-Module\0.6.9\Core\Protect-Win
                        dowsSecurity.psm1
Line                  :                 [System.Void]
                        [HardenWindowsSecurity.GUIMain]::app.Run([HardenWindowsSecurity.GUIMain]::mainGUIWindow)

Statement             : [System.Void]
                        [HardenWindowsSecurity.GUIMain]::app.Run([HardenWindowsSecurity.GUIMain]::mainGUIWindow)
PositionMessage       : At C:\Users\use\Documents\PowerShell\Modules\Harden-Windows-Security-Module\0.6.9\Core\Protect-
                        WindowsSecurity.psm1:325 char:17
                        + …             [System.Void] [HardenWindowsSecurity.GUIMain]::app.Run([H …
                        +               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PSScriptRoot          : C:\Users\use\Documents\PowerShell\Modules\Harden-Windows-Security-Module\0.6.9\Core
PSCommandPath         : C:\Users\use\Documents\PowerShell\Modules\Harden-Windows-Security-Module\0.6.9\Core\Protect-Win
                        dowsSecurity.psm1
InvocationName        :
PipelineLength        : 0
PipelinePosition      : 0
ExpectingInput        : False
CommandOrigin         : Internal
DisplayScriptPosition :
```

**Comment by HotCakeX** [comment]
Hi,
Thanks for reporting but this is a known issue in the build 24H2 that is fixed, and the fix is rolling out to users.
More info in this thread -> https://github.com/HotCakeX/Harden-Windows-Security/issues/368#issuecomment-2491984183

TL/TR

If you want to receive the fix, you need to install the preview update that is displayed in Windows Update page in Windows Settings. It'll become a mandatory update soon either way.
